swagger: '2.0'
info:
  title: MiMQIP Treatment Recommendation API
  description: MiMQIP Treatment Recommendation API
  version: "1.0.0"
host: api.mimqip.recommend
schemes:
  - https
basePath: /
produces:
  - application/json
paths:
  /messages:
    get:
      summary: Get messages by patientId
      description: Get messages by patientId
      operationId: getMessages
      tags:
        - message
      parameters:
        - name: patientId
          in: query
          description: Id of patient messages to fetch
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Array of messages
          schema:
            type: array
            items:
              $ref: '#/definitions/MessageDto'
definitions:
  MessageDto:
    type: object
    properties:
      id:
        type: integer
        format: int64
      priority:
        type: integer
        format: int32
      messageTag:
        type: string
      text:
        type: string
  Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        fields:
          type: string
