package org.flinnfoundation.model.enums;


public enum RuleType {
    CONSISTENT,
    STATUS,
    MEDICATIONS,
    GENERALCONSISTENCY,
    ADDITIONALCONSISTENCY,
    GENERALMESSAGES,
    CLINICALRESPONSE,
    MEDICALTRIAL,
    TREATMENTMESSAGES,
    SPECIALMESSAGES,
    OTHERMESSAGES,
    GUIDELINECHART,
    OTHERSIDEEFFECTS,
    OTHERREPORTS

}
